# Generated by Django 2.0.5 on 2018-06-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smokesession',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='smokesession',
            name='data',
        ),
    ]
