# Generated by Django 2.0.5 on 2018-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180611_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokesession',
            name='animal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smokesession',
            name='meatCut',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smokesession',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='smokesession',
            name='ogWeight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='smokesession',
            name='physDesc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='smokesession',
            name='trimWeight',
            field=models.IntegerField(null=True),
        ),
    ]
