# Generated by Django 2.0.5 on 2018-06-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180607_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smokesession',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='smokesession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='smokesession',
            name='meatCut',
        ),
        migrations.RemoveField(
            model_name='smokesession',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='smokesession',
            name='ogWeight',
        ),
        migrations.RemoveField(
            model_name='smokesession',
            name='physDesc',
        ),
        migrations.RemoveField(
            model_name='smokesession',
            name='trimWeight',
        ),
    ]
