# Generated by Django 2.0.5 on 2018-06-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180611_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokesession',
            name='ogWeight',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='smokesession',
            name='trimWeight',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
