# Generated by Django 2.0.5 on 2018-08-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180612_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smokesession',
            name='id',
        ),
        migrations.AlterField(
            model_name='smokesession',
            name='sessionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
