# Generated by Django 2.0.5 on 2018-09-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180821_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokesession',
            name='smoker',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
